### ISSUE TITLE
On mobile navbar load times are very slow

### ISSUE THREAD

**Issue by demanr** [deltahacks/landing-11#40]
When opening the website from a phone using the navbar takes a very long time from clicking where  you want to go and actually being directed to that location on the page

**Comment by fvcci** [comment]
Tested it out on my phone and I can replicate the issues. I also got a few more:
1. pressing the navbar permanently locks the screen on the navbar until reload. Pressing "x" does nothing
2. pressing the navigation items just don't work at all... :C

**Comment by fvcci** [comment]
Found the issue. Looks like the issue was the drawer dragging feature. It can be dragged from anywhere the drawer is clicked, but that makes it hard to distinguish between a drawer drag and a link select.

**Comment by arian81** [comment]
@fvcci is this issue fixed ?

**Comment by fvcci** [comment]
oh yeah it's been fixed.
